# Generated by Django 3.2 on 2022-04-08 09:41

import apps.home.utils
import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to=apps.home.utils.shp_file_directory_path)),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'SHP',
                'verbose_name_plural': 'SHP',
                'db_table': 'shp',
                'ordering': ('created_at',),
            },
        ),
    ]
