# Generated by Django 3.2 on 2022-04-08 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='uploaded_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
